#define MENU_PRINCIPAL '0'
#define CHARGER_UN_FICHIER '1'
#define AJOUTER_UN_DOSSIER '2'
#define CLOTURER_UN_DOSSIER '3'
#define SUPPRIMER_UN_COLLABORATEUR '4'
#define MODIFIER_UN_DOSSIER '5'
#define AJOUTER_UN_COLLABORATEUR '6'
#define MODIFIER_UN_COLLABORATEUR '7'
#define AFFICHER_LISTE_DOSSIER_SUIVI_COLLABORATEUR '8'
#define STATISTIQUE_COLLABRATEUR '9'
#define AFFICHER_INFORMATION_DOSSIER '10'


char affichageSelect_task(void);
