#define MENU_PRINCIPAL '0'
#define AFFICHER_INFORMATION_DOSSIER '1'
#define AFFICHER_LISTE_DOSSIER_SUIVI_COLLABORATEUR '2'
#define AJOUTER_UN_DOSSIER '3'
#define MODIFIER_UN_DOSSIER '4'
#define AJOUTER_UN_COLLABORATEUR '5'
#define MODIFIER_UN_COLLABORATEUR '6'
#define SUPPRIMER_UN_COLLABORATEUR '7'
#define SAUVEGARDE_FICHIER '8'

char affichageSelect_task(void);
