#define MENU_PRINCIPAL '0'
#define CHARGER_UN_FICHIER '1'
#define AJOUTER_UN_DOSSIER '2'
#define SUPPRIMER_UN_COLLABORATEUR '3'
#define MODIFIER_UN_DOSSIER '4'
#define AJOUTER_UN_COLLABORATEUR '5'
#define MODIFIER_UN_COLLABORATEUR '6'
#define AFFICHER_LISTE_DOSSIER_SUIVI_COLLABORATEUR '7'
#define STATISTIQUE_COLLABRATEUR '8'
#define AFFICHER_INFORMATION_DOSSIER '9'


char affichageSelect_task(void);
